sudo: false
language: scala
scala:
- 2.13.0
- 2.12.8
script:
- sbt ++$TRAVIS_SCALA_VERSION test
jdk:
- openjdk8
before_install:
- if [ $TRAVIS_PULL_REQUEST = 'false' ] && [ $TRAVIS_BRANCH = 'master' ]; then openssl
  aes-256-cbc -K $encrypted_42099b4af021_key -iv $encrypted_42099b4af021_iv -in travis/secrets.tar.enc
  -out travis/secrets.tar -d; tar xv -C travis -f travis/secrets.tar; fi
after_success:
- if [ $TRAVIS_PULL_REQUEST = 'false' ] && [ $TRAVIS_BRANCH = 'master' ]; then sbt
  ++$TRAVIS_SCALA_VERSION releaseEarly; fi
env:
  global:
  - secure: w8moldGQ50ayn/JQf0yGo0xIV6dO2FqJt4ZvMJ1aEctt3LopuHa++ZWcTMRCHb+I+impb828W/O0mI3enCVtyV1hmJbZCPTi9543zft6Gya7kTlmbWWnyg5gdbwpcQLJgDuN7jLCy+s3FpbyBUMrUQ4v2SfNcU7sx1YVzqK1MEad00+J/jLBPPFS6O+8mXix13VnCj+0bx60HdLB+2s+WslfUAhiq9ilAiNrsn+ngCPzrY2R5uwl3xQ/XE8/gUYz7XN6ugrWcBVPd8OXd9RMeFg73Wj+8f3ZCyD3lPFkc53Ix7+mk+2Rlbi+nrtFHJ8AL/IhnxlCpb8nu4J9FXpY+ZfdklhqYhnYPXgdS8Ewb7HHkwTBk4N3GrgKjAXu4fAi8XTnAbVSaodek8bXrVVr2/NPJod/GocdXUgyxYv5RrYusdfpnj2RPWvXEW/2UV30fLo90JkqN0ijhCWITLsC7GnSe7QU1zOoK/V2x7QKm+QApJAD9I5u718o80TKs1MBBuaHNmiopXN2h4qZjOAOZSOopTm4cNWGa4NRpPG8JSiM4t72PvCVdqhxHHGMhNv5rJvzWatB0H79aPxr8FtbiOYy2mB8oG2wAjCsu/fdwiIHubmdV4CB/bN/9QEkOdTy3C5+UGUvHjlE4NFYq4eD6vlq9RT0BxRH7Ob/3lp6DvM=
  - secure: usqiFrwr/Jt16rmPtC51vYhmC52Uupj3H9uE83nJXcaSIhNL0Z1reMbStTMrAWigT7RHU6YHqXGRlPAxabMwkg7F90oeCA6K84caINuU4Cf3zu7Z/WA+sS0LMsxolxnmiZ09JI/F0gaEGOqGVmKO1QjCNrHbqswwAhgauDwglUtM/uTIf08DXWATIA4M7WDbccVgL0w6eytavA82xyMZTrqTP0mvWM2d97d6H2pVpvgh7JZML/GDF0+M3QP15j9VdPjrfMh5im52OajReFl9kuOjacKx9voxP2BQsL814EZwvkqqI1zS1PKLBarBs2xDc2wPZyl8FdvZvmH3SLIomLdl50MBxlRmeP9JylztGQbPpWmaIwlKZj/rJxqdk9ZlYUql0evErWb3oyYpGV0NmFT6o05c+NJPs+XeFIUTsubteYO11NlE7MQVhnJmLpaT0YUPFkMA1JISif33QHtHrzuEvC7aGgZCxYsCpDN3A64hMLm8VTzgmYE7uQ52GlUCT3LRJV3mN49rCUOozGaAaY0M/lRF0RUHaiFWkRzqG0Qeb9n1ShopEbooaAnRBG4WbJl0oZBDwHAkUykUyIeZhPa5cho7Cf7TwBmK3DBP6fTjogCdE2yp6wpOdPg7ovLCFKB3MK0CAxcWPv46rP1OSTrK7FJr45E2CM3jfCRXk5c=
  - secure: ARl6mXZXwIP99VxsFIdXB/sPH0/8oA/PWQ1c+bbdojxZ62cRItvUfEJr9jo292n8dgDlcXQv0Vto26PDVnd6U33LrpwCaATi0q6RvxOTIHw15KYph1UpakeeM/Xmm2NEpMZ+92GM+71gMTy3RCGkvMUwIgjLGlkToKHFEVTErHtU0zXXxVOBZ9CEGWdtdGvmGon6DMT5l0v79FFC4Wp1AK3MKWMquVz+0vGKJGiUF9mbHPPbDlm/GjWi37og8TSp4/fE88x8JbuN/WS+x/aKo+st+HvvcbNYyA8v2aFKXG2qT7iE4YF5BhKmB4+9T6xbRAvFIdgDb2CmK2rJfGI0g2wIl47KsnZlmuN5X9WSCxFSBiuTLj/rSUl9m1ch9gmBzL3J+cVNcAWqR18jFQM9Pi0rkglUSPTvHSAAy4A2DnaSwHGtqY93NTaCFsk0Piv0t6QqVScmel9YWqQdzjd97CrK/hRKcoXWC9xDR/vN+3yjyK2Hg54h0suc4CbRkUVnvFaNi1ozYuR2Z0Z9vtdIs+pTUDvlqCZs/uveOMpa70+rP6Xo7mmAKMhYV145o0VKJLN/ALiFlKIZawRnzD6nRgzaejcQ/NH+kiuEySpHOXqQDSbqTm0m6aKlClNu8zbDeyVQ2aFqUKuw7tR436+GlgR+HV4GdP0ceoWkuVmtT7c=
